services:
  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      DB_HOST: postgres
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: user
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - postgres
      - redis

  bot:
    build:
      context: .
      dockerfile: ./bot/Dockerfile
    env_file: .env
    environment:
      REDIS_HOST: redis
      API_HOST: app
    depends_on:
      - postgres
      - redis
      - app

  postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
