"""todo table

Revision ID: cf553ceeb689
Revises: cc50d2de5b98
Create Date: 2025-05-05 13:08:48.268518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf553ceeb689'
down_revision: Union[str, None] = 'cc50d2de5b98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('data_of_creation', sa.Date(), nullable=False),
    sa.Column('data_of_change', sa.Date(), nullable=False),
    sa.Column('doer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doer_id'], ['bot_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_todo_doer_id'), 'todo', ['doer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_todo_doer_id'), table_name='todo')
    op.drop_table('todo')
    # ### end Alembic commands ###
